### ISSUE TITLE
Project management: write status report 1

### ISSUE THREAD

**Issue by olleblo** [IL2232-HT2022-HIL/IL2232-HT2022-HIL#19]
In this course, two status reports are mandatory to hand in. This will be the first of the two status reports and its due date is on Monday the 7th of November at 23:59.

The status report should follow up on aspects from the project plan that are completed, and on any changes made. The risk report should be revisited and the time and resource plan updated.

Link to document:
https://www.overleaf.com/8824793115tchrqjjspfgp

To do:

- [x] create skeleton document in overleaf
- [x] partition the workload 
- [x] inform team-mates on what parts need work
- [ ] upload first draft to github for matthias to review
- [ ] address any comments on updates
- [x] hand in on canvas

**Comment by sofiecmf** [comment]
sofie will make sure it is produced and handed in

**Comment by sofiecmf** [comment]
What parts can be spiced up?

- [x] Current status: Review stated progress on deliverables and correct/elaborate if you want to. @ all
- [x] Current status: Add anything else that you think should be mentioned about the period between the project plan - the first status report. @ all
- [x] Current status: Comment on the risk report. @sofiecmf 

- [x] Resource state: Update the timing sheet so that our numbers can be more up to date. @ all
- [x] Resource state: When the sheet is updated, discuss the new result. @sofiecmf 

- [x] **Challenges: I suggested two aspects of the project that I felt had been seen as challenging. Please elaborate on these if you agree, or change them into something else if they are not relevant. @ all**
- [x] **Challenges: When we agree on the challenges presented, we should also come up with proposed measures for how to relieve these hardships. @ all**

- [x] Alterations: Have we made any formal changes to the project? (Maybe related to our challenges?) If so, please state them here. @ all

- [x] Appendices: Update and upload gantt chart and resource plan. @sofiecmf
